name: readme_sync

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - v1.0

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      # Run GitHub Action to sync docs in `documentation` directory
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @v10
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          rdme: docs upload ./documentation --key=${{ secrets.README_API_KEY }} --branch=2.0
