name: readme_sync

on:
  push:
    branches:
      - v1.0

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Sync guides (./docs)
        uses: readmeio/rdme@v10
        with:
          rdme: docs upload ./docs --key=${{ secrets.README_API_KEY }} ----branch=1.0

      - name: Sync API reference (./reference)
        uses: readmeio/rdme@v10
        with:
          rdme: reference upload ./reference --key=${{ secrets.README_API_KEY }} ----branch=1.0
